### ISSUE TITLE
Add Unit Testing for PlayerAPI

### ISSUE THREAD

**Issue by mikamerath** [michaelkamerath/SharedServer#22]
The Player API code still doesn't have unit tests to verify functionality. The tests need to be updated in order to ensure full coverage of the API code

**Comment by Frangello** [comment]
@michaelkamerath do you know what could be causing this problem on the Test CMakeList.txt? 
`CMake Error at CMakeLists.txt:1 (xpGetExtern):
  Unknown CMake command "xpGetExtern".
`

**Comment by davidbrowning** [comment]
I'm not sure, but I'm getting a similar error whenever I try to build it. 

```
    CMake Error at Findexternpro.cmake:100 (message):
    externpro 16.07.1-vc140-64 not found
    Call Stack (most recent call first):
    CMakeLists.txt:14 (find_package)
```

I ran sundberg's windows installer with default settings, and I have MSVC++ 14 running on 64 bit windows 8.1. Cmake version 3.6.2. No dice...

**Comment by C-Merrill** [comment]
@davidbrowning: when you run cmake, try it with the flag <code>-G "Visual Studio 14 Win64"</code>. For me at least, cmake default builds for win32, but your externpro is a 64-bit version, so it won't find a 32-bit version.

**Comment by mikamerath** [comment]
@Frangello can you link your CMakeList.txt file so I can take a look at it?

**Comment by davidbrowning** [comment]
![extern](https://cloud.githubusercontent.com/assets/16102754/20073439/8844b58e-a4e9-11e6-8ba3-f287a9dba382.PNG)

**Comment by Frangello** [comment]
@michaelkamerath I haven't changed CMakeList.txt, I cloned everything from the repo and only changed test.cpp

**Comment by mikamerath** [comment]
@davidbrowning The error looks like you might not have externpro installed correctly if you are still getting that error. Can you please verify that you installed it completely and correctly and then get back to me?

**Comment by katiesweet** [comment]
@davidbrowning Sundberg's prebuilt version is for version 16.10.3. Michael's CMakeLists.txt is looking for a version 16.07.1, so you need to manually change the CMakeLists.txt file locally to look for the correct version. Also, I thought Sundberg's prebuilt version was for Linux operating systems since the Windows executable already exists. It might still work though.

**Comment by Frangello** [comment]
@michaelkamerath do you know what is happening? 
![virtualbox_ubuntu 64bit_10_11_2016_20_32_32](https://cloud.githubusercontent.com/assets/15683151/20203734/2f6a1c56-a787-11e6-9c64-3b81936cca10.png)

**Comment by mikamerath** [comment]
@Frangello I'm unsure, try updating to the latest version and see if that fixes your CMake errors

**Comment by Frangello** [comment]
@michaelkamerath I did a git pull right before that

**Comment by mikamerath** [comment]
@Frangello Did you fetch before you pulled? Your background looks like you were behind at the time this was executed
