### ISSUE TITLE
Update to Externpro 16.10.3

### ISSUE THREAD

**Issue by mikamerath** [michaelkamerath/SharedServer#36]
On 11/12/2016, we'll be updating to Externpro 16.10.3. Install the newer version of externpro by then to keep up to date

**Comment by mikamerath** [comment]
@C-Merrill Please make this a pull request next time and link it in a comment so we can keep track of these things. Silently changing things is bad

**Comment by C-Merrill** [comment]
Yeah I didn't mean to push that sorry.
