### ISSUE TITLE
Fix CMake issues for building on Linux

### ISSUE THREAD

**Issue by mikamerath** [michaelkamerath/SharedServer#39]

**Comment by mikamerath** [comment]
Pull Request: https://github.com/michaelkamerath/SharedServer/pull/40

**Comment by Frangello** [comment]
I've installed all kinds of libboost and still get this error
![virtualbox_ubuntu 64bit_15_11_2016_22_38_52](https://cloud.githubusercontent.com/assets/15683151/20336028/74cf3726-ab84-11e6-9bf2-408a55cb5874.png)

**Comment by mikamerath** [comment]
Pull Request: https://github.com/michaelkamerath/SharedServer/pull/40
